[project]
name = "shroom-bot"
version = "0.1.0"
description = "Just a happy little shroom boi"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
license-files = ["LICENSE"]
dependencies = [
    "aiohttp>=3.13.2",
    "aiosqlite>=0.22.1",
    "attrs>=25.4.0",
    "discord-py>=2.6.4",
    "python-dotenv>=1.2.1",
]
